include base.mk

WEB_SHELL ?= web.html
WEB_MAIN ?= web.c
WEB_STACK_SIZE ?= 1048576
WEB_HEAP_SIZE ?= 67108864

CC = emcc

CFLAGS = \
	-DWEB_BUILD \
	-sUSE_GLFW=3 \
	-sGL_ENABLE_GET_PROC_ADDRESS \
	-sSTACK_SIZE=$(WEB_STACK_SIZE) \
	-sTOTAL_MEMORY=$(WEB_HEAP_SIZE) \
	-sERROR_ON_UNDEFINED_SYMBOLS=0

LDFLAGS = -lraylib

PLATFORM_OBJ = $(PLATFORM_OUT_DIR)/$(GAME_CODE).o
PLATFORM_ZIP = $(PLATFORM_OUT_DIR)/$(GAME_CODE)-$(GAME_VERSION).zip

PLATFORM_HTML = $(PLATFORM_OUT_DIR)/index.html
PLATFORM_JS = $(PLATFORM_OUT_DIR)/index.js
PLATFORM_WASM = $(PLATFORM_OUT_DIR)/index.wasm
PLATFORM_ASSETS = $(PLATFORM_OUT_DIR)/index.data

# Build object file
$(PLATFORM_OBJ): $(PLATFORM_DOCKER_TARGET) $(ODIN_SOURCES)
	$(DOCKER_RUN) $(ODIN) build $(SRC_DIR) $(ODIN_FLAGS) -build-mode:obj -target=freestanding_wasm32 -out:$(PLATFORM_OBJ)

$(PLATFORM_HTML) $(PLATFORM_JS) $(PLATFORM_WASM) $(PLATFORM_ASSETS): $(PLATFORM_OBJ) $(ASSETS_FILES)
	$(DOCKER_RUN) $(CC) $(WEB_MAIN) $(PLATFORM_OBJ) -o $(PLATFORM_HTML) $(CFLAGS) $(LDFLAGS) --shell-file $(WEB_SHELL)

.PHONY: run

.DEFAULT_GOAL = $(PLATFORM_HTML)
